name: CI to APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer Cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          
      - name: Force Pre-accepted Android SDK Licenses
        run: |
          # إنشاء مسارات التراخيص التي يعتمد عليها sdkmanager داخلياً
          SDK_DIR="/home/runner/.buildozer/android/platform/android-sdk"
          mkdir -p $SDK_DIR/licenses
          
          # حقن رموز التراخيص المقبولة لمنع أي توقف تفاعلي نهائياً
          echo "24333f8a43b681427c30427efe84f2c0ab4748d1" > $SDK_DIR/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" >> $SDK_DIR/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6488e" >> $SDK_DIR/licenses/android-sdk-license
          echo "504667f4c0de7af1a06de9f4b1727b8ad351d663" >> $SDK_DIR/licenses/android-sdk-license

      - name: Build with Buildozer
        env:
          ANDROIDAPI: "33"
          ANDROIDMINAPI: "24"
        run: |
          buildozer -v android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sttiten-receiver-apk
          path: bin/*.apk
          
