name: CI to APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer Cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          
      - name: Configure Android Environment & Licenses
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/licenses
          sudo chmod -R 777 /usr/local/lib/android/sdk
          
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > /usr/local/lib/android/sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" >> /usr/local/lib/android/sdk/licenses/android-sdk-license
          echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6488e" >> /usr/local/lib/android/sdk/licenses/android-sdk-license

      - name: Build with Buildozer
        env:
          ANDROIDSDK: /usr/local/lib/android/sdk
          ANDROIDNDK: /usr/local/lib/android/sdk/ndk/27.3.13750724
          ANDROIDAPI: "33"
          ANDROIDMINAPI: "24"
        run: |
          # استخدام مستوى تتبع أعلى (log_level 2 مضمن) وتوجيه المخرجات بوضوح
          buildozer -v android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sttiten-receiver-apk
          path: bin/*.apk
          
